### ISSUE TITLE
Validation datasets

### ISSUE THREAD

**Issue by rubensworks** [ldbc/ldbc_snb_datagen_hadoop#18]
Hi there 👋 Thanks for the work on this benchmark!

I'm currently attempting to use this benchmark to measure the correctness of some systems.
I'm not using the [driver](https://github.com/ldbc/ldbc_snb_interactive_driver), and I'm instead generating the dataset directly, and running the (interactive) queries manually.
I was wondering if you could provide any pointers on how to obtain a validation dataset?

I found this [wiki page](https://github.com/ldbc/ldbc_snb_interactive_driver/wiki/Validating-a-Database-Connector), but it seems to suggest that a validation dataset for the interactive queries should already exist somewhere:

> It is the responsibility of the workload developer to also provide a validation dataset and validation operation set, which others can then use to test their database connector implementations.

Is there a place where I can find this dataset and operation set? Or can I generate it myself somehow?

I found [this file](https://github.com/ldbc/ldbc_snb_interactive_impls/blob/c19be0e793680497de4e88d360a20708cfcf43a9/sparql/validation_params_only_complex.csv) that appears to be a validation operation set, but it is unclear what dataset this should be run on, or what scale factor was used to generate the required dataset.

Thanks in advance for the help.

**Comment by szarnyasg** [comment]
Hi Ruben!

Here's a package of the validation data sets that we are currently using: https://surfdrive.surf.nl/files/index.php/s/opeAtUOUSbxtXTQ/download

This was generated on scale factors 1, 3, 10, and 30 with the Neo4j system.

Note that we have since discovered a potential issue with leap seconds on Interactive Complex query 7:
https://github.com/ldbc/ldbc_snb_docs/issues/209
This data set was generating UTC-SLS, while other systems may use vanilla UTC plus leap seconds. Therefore, the `minutesLatency` attribute may have a difference of plus/minus 1 in rare cases.

**Comment by rubensworks** [comment]
Thanks for the quick reply, this is exactly what I was looking for 🙂 

> https://surfdrive.surf.nl/files/index.php/s/opeAtUOUSbxtXTQ/download

Will this link remain active?
If not, am I allowed to redistribute this myself?
I'm asking because I would like to enable reproducibility.

**Comment by szarnyasg** [comment]
Sure, feel free to redistribute it

**Comment by rubensworks** [comment]
Thanks!
